# Generated by Django 4.1.3 on 2022-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0002_bookings_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_rating',
            old_name='Local_Name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Package',
            field=models.CharField(max_length=120, verbose_name='Packages'),
        ),
    ]
