# Generated by Django 4.1.3 on 2022-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('a_rooms', models.IntegerField(max_length=120, verbose_name='available rooms')),
                ('premium_pack', models.CharField(max_length=120, verbose_name='premium')),
                ('normal_pack', models.CharField(max_length=120, verbose_name='normal')),
                ('budget_pack', models.CharField(max_length=120, verbose_name='budget')),
                ('Details', models.CharField(max_length=120, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('password', models.CharField(max_length=120, verbose_name='password')),
                ('location_id', models.CharField(max_length=120, verbose_name='Location')),
                ('a_rooms', models.IntegerField(max_length=120, verbose_name='available rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='first name')),
                ('second_name', models.CharField(max_length=120, verbose_name='last name')),
                ('location', models.CharField(max_length=120, verbose_name='location')),
                ('number', models.IntegerField(verbose_name='phone number')),
                ('password', models.CharField(max_length=120, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='POI_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POI_name', models.CharField(max_length=120, verbose_name='POI_Name')),
                ('location', models.CharField(max_length=30, verbose_name='POI_location')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120, verbose_name='Tourist ID')),
                ('cnic', models.IntegerField(verbose_name='CNIC')),
                ('first_name', models.CharField(max_length=120, verbose_name='first name')),
                ('las_name', models.CharField(max_length=120, verbose_name='last name')),
                ('location', models.CharField(max_length=120, verbose_name='location')),
                ('password', models.CharField(max_length=120, verbose_name='password')),
                ('book_id', models.CharField(max_length=120, verbose_name='booking ID')),
                ('number', models.IntegerField(verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='trip_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tourist_Name', models.CharField(max_length=120, verbose_name='Tourist_Name')),
                ('Choose_POI1', models.CharField(max_length=120, verbose_name='POI_Name1')),
                ('Choose_POI2', models.CharField(max_length=120, verbose_name='POI_Name2')),
                ('Choose_POI3', models.CharField(max_length=120, verbose_name='POI_Name3')),
                ('Choose_Hotel1', models.CharField(max_length=120, verbose_name='Hotel_Name1')),
                ('Choose_Hotel2', models.CharField(max_length=120, verbose_name='Hotel_Name2')),
            ],
        ),
        migrations.CreateModel(
            name='POI_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local_Name', models.CharField(max_length=120, verbose_name='Local Name')),
                ('Rating', models.IntegerField(max_length=120, verbose_name='Rating')),
                ('Review', models.CharField(max_length=120, verbose_name='Review')),
                ('Choose_POI', models.ManyToManyField(blank=True, to='tourists.poi_add')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local_Name', models.CharField(max_length=120, verbose_name='Local Name')),
                ('Rating', models.IntegerField(max_length=120, verbose_name='Rating')),
                ('Review', models.CharField(max_length=120, verbose_name='Review')),
                ('Choose_Hotel', models.ManyToManyField(blank=True, to='tourists.hotel_add')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Customer Name')),
                ('sdate', models.DateField(verbose_name='Start date')),
                ('edate', models.DateField(verbose_name='End date')),
                ('Choose_Hotel', models.ManyToManyField(blank=True, to='tourists.hotel_add')),
            ],
        ),
    ]
