# Generated by Django 4.1.3 on 2022-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POI_id', models.CharField(max_length=120, verbose_name='hotel ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('Rating', models.IntegerField(max_length=120, verbose_name='rating')),
                ('Review', models.IntegerField(max_length=120, verbose_name='review')),
            ],
        ),
    ]
