# Generated by Django 4.1.3 on 2022-11-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0002_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='POI_id',
        ),
    ]
