# Generated by Django 4.1.3 on 2022-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0003_rename_local_name_hotel_rating_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_rating',
            name='Name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
