# Generated by Django 4.1.3 on 2022-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0004_poi_rating_remove_poi_rating_remove_poi_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POI_name', models.CharField(max_length=120, verbose_name='name')),
                ('location', models.IntegerField(max_length=30, verbose_name=' rating ')),
            ],
        ),
        migrations.RenameField(
            model_name='poi_rating',
            old_name='name',
            new_name='Local_Name',
        ),
        migrations.AlterField(
            model_name='poi_rating',
            name='Rating',
            field=models.CharField(max_length=120, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='poi_rating',
            name='Review',
            field=models.CharField(max_length=120, verbose_name='Location'),
        ),
        migrations.DeleteModel(
            name='POI',
        ),
        migrations.AddField(
            model_name='poi_rating',
            name='Rating_Review',
            field=models.ManyToManyField(blank=True, to='tourists.poi_add'),
        ),
    ]
