# Generated by Django 4.1.3 on 2022-12-09 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0004_alter_hotel_rating_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi_rating',
            name='Local_Name',
        ),
        migrations.AddField(
            model_name='poi_rating',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
