# Generated by Django 4.1.3 on 2022-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0005_poi_add_rename_name_poi_rating_local_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poi_rating',
            old_name='Rating_Review',
            new_name='Choose_POI',
        ),
        migrations.AlterField(
            model_name='poi_add',
            name='POI_name',
            field=models.CharField(max_length=120, verbose_name='POI_Name'),
        ),
        migrations.AlterField(
            model_name='poi_add',
            name='location',
            field=models.CharField(max_length=30, verbose_name='POI_location'),
        ),
        migrations.AlterField(
            model_name='poi_rating',
            name='Local_Name',
            field=models.CharField(max_length=120, verbose_name='Local Name'),
        ),
        migrations.AlterField(
            model_name='poi_rating',
            name='Rating',
            field=models.IntegerField(max_length=120, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='poi_rating',
            name='Review',
            field=models.CharField(max_length=120, verbose_name='Review'),
        ),
    ]
