# Generated by Django 4.1.3 on 2022-11-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0006_rename_rating_review_poi_rating_choose_poi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locals',
            name='local_id',
        ),
    ]
