# Generated by Django 4.1.3 on 2022-11-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0007_remove_locals_local_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('password', models.CharField(max_length=120, verbose_name='password')),
                ('location_id', models.CharField(max_length=120, verbose_name='Location')),
                ('a_rooms', models.IntegerField(max_length=120, verbose_name='available rooms')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='hotel_id',
        ),
        migrations.CreateModel(
            name='Hotel_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local_Name', models.CharField(max_length=120, verbose_name='Local Name')),
                ('Rating', models.IntegerField(max_length=120, verbose_name='Rating')),
                ('Review', models.CharField(max_length=120, verbose_name='Review')),
                ('Choose_Hotel', models.ManyToManyField(blank=True, to='tourists.hotel_add')),
            ],
        ),
    ]
