# Generated by Django 4.1.3 on 2022-11-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0008_hotel_add_remove_hotels_hotel_id_hotel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_add',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='hotel_add',
            name='password',
        ),
    ]
