# Generated by Django 4.1.3 on 2022-11-30 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0010_hotels_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='Details',
        ),
        migrations.AddField(
            model_name='hotel_add',
            name='Details',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Details'),
            preserve_default=False,
        ),
    ]
