# Generated by Django 4.1.3 on 2022-11-30 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0011_remove_hotels_details_hotel_add_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_add',
            name='budget_pack',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_add',
            name='normal_pack',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='normal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_add',
            name='premium_pack',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='premium'),
            preserve_default=False,
        ),
    ]
