# Generated by Django 4.1.3 on 2022-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0012_hotel_add_budget_pack_hotel_add_normal_pack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tourist_Name', models.CharField(max_length=120, verbose_name='Local Name')),
                ('Choose_Hotel', models.ManyToManyField(blank=True, to='tourists.hotel_add')),
                ('Choose_POI', models.ManyToManyField(blank=True, to='tourists.poi_add')),
            ],
        ),
    ]
