# Generated by Django 4.1.3 on 2022-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0013_trip_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_add',
            name='Tourist_Name',
            field=models.CharField(max_length=120, verbose_name='Tourist_Name'),
        ),
    ]
