# Generated by Django 4.1.3 on 2022-12-08 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0014_alter_trip_add_tourist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_add',
            name='Choose_Hotel',
        ),
        migrations.RemoveField(
            model_name='trip_add',
            name='Choose_POI',
        ),
        migrations.AddField(
            model_name='trip_add',
            name='Choose_Hotel1',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Hotel_Name1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip_add',
            name='Choose_Hotel2',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Hotel_Name2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip_add',
            name='Choose_POI1',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='POI_Name1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip_add',
            name='Choose_POI2',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='POI_Name2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip_add',
            name='Choose_POI3',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='POI_Name3'),
            preserve_default=False,
        ),
    ]
