# Generated by Django 4.1.3 on 2022-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0015_remove_trip_add_choose_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('sdate', models.DateField(verbose_name='sdate')),
                ('edate', models.DateField(verbose_name='edate')),
                ('Choose_Hotel', models.ManyToManyField(blank=True, to='tourists.hotel_add')),
            ],
        ),
    ]
